# Generated by Django 3.2.7 on 2021-09-11 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_alter_video_video_id'),
        ('playlists', '0003_auto_20210911_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platlist_featured', to='videos.video'),
        ),
    ]
