# Generated by Django 3.2.7 on 2021-09-14 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0011_movieproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieproxy',
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
    ]
